### ISSUE TITLE
FEATURE: Add Liquidity on any Curve Pool

### ISSUE THREAD

**Issue by taariq** [VolumeFi/exchange-liquidity#2]
As a user, I want to call a VolumeFi vyper contract to trade into any Curve pool that will check my balance and either exchange my balance for USDC or WETH using Curve or will trade my USDC or WETH into Curve so that I will be able to add to the Curve Pool in which I want to trade.

**Requirements**
Flow of read and write transactions on ETH
1. Read balance in USDC or ETH on trading account

3. Convert ETH into other pool token if I do not have the token in my balance
4. Deposit into the Curve pool the desired amount.
5. We will limit to USDC and ETH
6. We will limit to convert USDC to ETH using Uniswap
7. We will convert ETH to Curve Pool pair in order to deposit to the pool
8. The contract will charge 0.010 ETH fee per transaction for all transactions.

**Acceptance Criteria**
1. This Vyper contract should be testable with a Uniswap type interface to any Curve Token/WETH or Token/USDC pool where the token balance requires a token purchase and where the user has either USDC or WETH
2. This contract will charge a 0.005 ETH per transaction fee for each transaction that is successful and not reverted. The contract will pay the fee to the ETH address given.

**Comment by webelf101** [comment]
Regarding the following ticket
7. The contract will charge 0.005 ETH fee per transaction for all transactions over $5,000. So pricing is 0.005 ETH per transaction at a minimum transaction of $5,000 USDC. Anything less is zero cost.

In my opinion, we need to set 0.005ETH fee to every transaction.
Because confirming the transaction amount greater than 5K will spend more gas than 0.005ETH so it is not really useful.

**Comment by taariq** [comment]
@webelf101 updated so that fee is standard for all transactions.

**Comment by taariq** [comment]
Delivered.
